### PR TITLE
Postres tests

### PR DESCRIPTION
**Pull request by cmbrose**
Unit tests for the postres package.  Nothing pressing, just noticed that one of the handler tests was failing and wanted to fix it.

### CODE REVIEW

**Comment by cmbrose** [comment]
@theMagicalKarp (this is relying on your current PR)
@chfogerty

**Comment by nickmonad** [comment]
+1

**Comment by nickmonad** [comment]
Haha didn't notice I wasn't tagged. Take a free +1 anyway!

**Comment by chfogerty** [comment]
+1

**Comment by cmbrose** [comment]
@lighthouse/owners the only change here is a test so I'm going to go ahead and merge it.

**Pull request merged**
