### PR TITLE
Test beacon validity on create

### PR DESCRIPTION
**Pull request by cmbrose**
If there is an error getting the VMs from a beacon in `/beacons/create` then the beacon (and alias) are not added.  An error is returned, just like it was originally.

### CODE REVIEW

**Comment by nickmonad** [comment]
Can we dial back the timeouts?

```
2015/03/30 15:25:47   42.29058ms GET /api/v0.2/beacons/list/192.168.59.103:5000
2015/03/30 15:26:34 30.131982895s POST /api/v0.2/beacons/create
2015/03/30 15:28:51 30.086733297s POST /api/v0.2/beacons/create
```

**Comment by cmbrose** [comment]
@ngmiller definitely!  What seems reasonable? 3 seconds?

**Comment by nickmonad** [comment]
Sounds good for now :)

**Comment by cmbrose** [comment]
@ngmiller can you check that this the timeout works now? On my machine I get a connection refusal almost immediately (it doesn't timeout).

**Comment by nickmonad** [comment]
@cmbrose Works for me! +1

**Pull request merged**
