### PR TITLE
Bugfix - don't duplicate query params

### PR DESCRIPTION
**Pull request by cmbrose**
Removed lines which duplicated the query params

### CODE REVIEW

**Comment by cmbrose** [comment]
@lighthouse/owners for your review

**Comment by chfogerty** [comment]
I think coveralls broke. +1

**Comment by cmbrose** [comment]
Possibly something wrong in the coverage script https://travis-ci.org/lighthouse/lighthouse/builds/53007629#L335

**Comment by cmbrose** [comment]
@ngmiller @theMagicalKarp will this fix the issue for you guys?

**Pull request merged**
