### PR TITLE
General Unit Tests

### PR DESCRIPTION
**Pull request by robertsheehy-wf**
## What

Some unit tests for a few packages in Lighthouse.
## Try it

`go test $GOPATH/github.com/lighthouse/lighthouse/...` or `go test ./...` depending where you are.
## Notes

I didn't get 100% coverage, but I tackled most of the basic functions.  A big pain point right now for me is, not being able to easily Mock/Patch functions as dynamically as I'm used to in python :(. I'm also having trouble testing functions that utilize the database. I tried using [go-sqlmock](https://github.com/DATA-DOG/go-sqlmock), but I was getting back false positives from the asserts, which was frustrating.

### CODE REVIEW

**Comment by robertsheehy-wf** [comment]
@chfogerty @zach-taylor @cmbrose @ngmiller

**Comment by cmbrose** [comment]
@theMagicalKarp have you looked at [Testify mocks](https://github.com/stretchr/testify#mock-package) for mocking?  I'm not sure if it's what you need or not, but it might help.

**Comment by robertsheehy-wf** [comment]
@cmbrose I briefly tried those, I'm not sure how they work though since go is a statically typed language.  How do I pass a Mock object to function that requires, for example, a `*sql.DB` object.

```
cannot use testObj (type *mock.Mock) as type *sql.DB in field value
```

**Comment by cmbrose** [comment]
+1 these work for me

**Comment by cmbrose** [comment]
I also have a solution to the mocking coming in my next PR

**Comment by theMagicalKarp** [comment]
Well to help out with the diffs in #21 I'll merge this. This is pretty benign as far as functionality goes.

**Pull request merged**
