### PR TITLE
Revised url prefix for login/logout to "/api/v0.1"

### PR DESCRIPTION
**Pull request by robertsheehy-wf**
screen shot 2014-11-20 at 8 50 36 am

### CODE REVIEW

**Comment by robertsheehy-wf** [comment]
@chfogerty @ngmiller @zach-taylor @cmbrose

**Comment by cmbrose** [comment]
@ngmiller do you want all the provider endpoints to have that prefix as well?

**Comment by nickmonad** [comment]
Looks good! +1
@cmbrose I think it makes sense to have any routes not serving static assets go through the API router

**Comment by zach-taylor** [comment]
+1

**Comment by cmbrose** [comment]
+1

**Pull request merged**
