### PR TITLE
Go fmt-ed all code

### PR DESCRIPTION
**Pull request by cmbrose**
Simply ran `go fmt ./...`.  This will standardize our formatting.

### CODE REVIEW

**Comment by cmbrose** [comment]
@lighthouse/owners

**Comment by nickmonad** [comment]
+1

**Comment by robertsheehy-wf** [comment]
+1

**Comment by zach-taylor** [comment]
Do we want to make this part of the build to ensure all PR's follow the Go formatting standards?

**Comment by nickmonad** [comment]
image

**Comment by cmbrose** [comment]
@zach-taylor, good idea.  Added it.

**Comment by zach-taylor** [comment]
Awesome! +1

**Comment by cmbrose** [comment]
@chfogerty any thoughts?

**Comment by chfogerty** [comment]
+1

**Pull request merged**
