### PR TITLE
Pull harbor dependencies in docker image

### PR DESCRIPTION
**Pull request by theMagicalKarp**

### CODE REVIEW

**Comment by cmbrose** [comment]
+1

**Comment by zach-taylor** [comment]
+1

**Comment by nickmonad** [comment]
+1 with passing build

**Comment by cmbrose** [comment]
@ngmiller the break in the build is from the Go version update.  I will have a PR out to fix this soon, but this is OK up to version 1.3.

**Comment by nickmonad** [comment]
+1

**Comment by cmbrose** [comment]
Build will be repaired with https://github.com/lighthouse/lighthouse/pull/68

**Pull request merged**
